server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xfhucyazhkfwhe:e8f9d693b85b81270551644660cce7a06a2949d32837bcc230215e0ab4440565@ec2-50-17-255-120.compute-1.amazonaws.com:5432/d2b2e9evludoos
    username: xfhucyazhkfwhe
    password: e8f9d693b85b81270551644660cce7a06a2949d32837bcc230215e0ab4440565
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend